version: '3.9'

services:
  backend:
    container_name: node_nest
    build: ./docker/node
    tty: true
    volumes:
      - "~/.ssh:/root/.ssh"
      - ".:/root/app"
    working_dir: "/root/app"
    networks:
      - app-network
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
    networks:
      - app-network
  
networks:
  app-network: